(ns nvidia_isaac.actor
  "nvidia_isaac clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Robotics simulation / manipulation (Isaac-style) physical-AI.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; SimRobot
   {:db/ident :nvidia_isaac.SimRobot/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_isaac.SimRobot/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimRobot/embodiment :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimRobot/dof :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimRobot/urdf :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimRobot/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimRobot/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Skill
   {:db/ident :nvidia_isaac.Skill/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_isaac.Skill/robotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Skill/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Skill/policyType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Skill/successRate :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Skill/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Skill/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SimScene
   {:db/ident :nvidia_isaac.SimScene/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_isaac.SimScene/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimScene/assets :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimScene/domainRandomized :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimScene/physicsDt :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimScene/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.SimScene/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Policy
   {:db/ident :nvidia_isaac.Policy/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_isaac.Policy/skillId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Policy/algorithm :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Policy/checkpoint :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Policy/reward :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Policy/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Policy/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Sensor
   {:db/ident :nvidia_isaac.Sensor/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_isaac.Sensor/robotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Sensor/modality :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Sensor/rateHz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Sensor/resolution :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Sensor/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Sensor/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Trajectory
   {:db/ident :nvidia_isaac.Trajectory/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_isaac.Trajectory/robotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Trajectory/waypoints :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Trajectory/durationS :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Trajectory/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Trajectory/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_isaac.Trajectory/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"SimRobot" "Skill" "SimScene" "Policy" "Sensor" "Trajectory"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "nvidia_isaac: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "nvidia_isaac: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "nvidia_isaac: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── SimRobot ────────────────────────────────────────────────────────────────
(defn create-sim-robot
  "Create a SimRobot."
  [port data]
  (require-fields data ["name" "embodiment"])
  (let [id (new-id "isaac_sim")
        e {:db/id id
           :nvidia_isaac.SimRobot/id id
           :nvidia_isaac.SimRobot/name (get data :name)
           :nvidia_isaac.SimRobot/embodiment (get data :embodiment)
           :nvidia_isaac.SimRobot/dof (as-long (get data :dof))
           :nvidia_isaac.SimRobot/urdf (get data :urdf)
           :nvidia_isaac.SimRobot/createdAt (now)
           :nvidia_isaac.SimRobot/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-sim-robots
  "List SimRobot with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-sim-robots port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_isaac.SimRobot/id))
         rows (apply-filters rows (:filter opts) [:nvidia_isaac.SimRobot/name :nvidia_isaac.SimRobot/embodiment :nvidia_isaac.SimRobot/dof :nvidia_isaac.SimRobot/urdf])]
     (paginate rows opts))))

(defn get-sim-robot
  "Retrieve a SimRobot by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-sim-robot port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-sim-robot
  "Update a SimRobot; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :nvidia_isaac.SimRobot/name (get data :name)]))
                   (cond-> (contains? data :embodiment) (conj [:db/add id :nvidia_isaac.SimRobot/embodiment (get data :embodiment)]))
                   (cond-> (contains? data :dof) (conj [:db/add id :nvidia_isaac.SimRobot/dof (as-long (get data :dof))]))
                   (cond-> (contains? data :urdf) (conj [:db/add id :nvidia_isaac.SimRobot/urdf (get data :urdf)]))
                   (conj [:db/add id :nvidia_isaac.SimRobot/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-sim-robot
  "Delete a SimRobot."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Skill ────────────────────────────────────────────────────────────────
(defn create-skill
  "Create a Skill."
  [port data]
  (require-fields data ["name" "policyType"])
  (let [id (new-id "isaac_ski")
        e {:db/id id
           :nvidia_isaac.Skill/id id
           :nvidia_isaac.Skill/robotId (get data :robotId)
           :nvidia_isaac.Skill/name (get data :name)
           :nvidia_isaac.Skill/policyType (get data :policyType)
           :nvidia_isaac.Skill/successRate (as-double (get data :successRate))
           :nvidia_isaac.Skill/createdAt (now)
           :nvidia_isaac.Skill/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-skills
  "List Skill with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-skills port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_isaac.Skill/id))
         rows (apply-filters rows (:filter opts) [:nvidia_isaac.Skill/robotId :nvidia_isaac.Skill/name :nvidia_isaac.Skill/policyType :nvidia_isaac.Skill/successRate])]
     (paginate rows opts))))

(defn get-skill
  "Retrieve a Skill by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-skill port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-skill
  "Update a Skill; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :robotId) (conj [:db/add id :nvidia_isaac.Skill/robotId (get data :robotId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :nvidia_isaac.Skill/name (get data :name)]))
                   (cond-> (contains? data :policyType) (conj [:db/add id :nvidia_isaac.Skill/policyType (get data :policyType)]))
                   (cond-> (contains? data :successRate) (conj [:db/add id :nvidia_isaac.Skill/successRate (as-double (get data :successRate))]))
                   (conj [:db/add id :nvidia_isaac.Skill/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-skill
  "Delete a Skill."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SimScene ────────────────────────────────────────────────────────────────
(defn create-sim-scene
  "Create a SimScene."
  [port data]
  (require-fields data ["name" "assets"])
  (let [id (new-id "isaac_sim")
        e {:db/id id
           :nvidia_isaac.SimScene/id id
           :nvidia_isaac.SimScene/name (get data :name)
           :nvidia_isaac.SimScene/assets (as-long (get data :assets))
           :nvidia_isaac.SimScene/domainRandomized (as-bool (get data :domainRandomized))
           :nvidia_isaac.SimScene/physicsDt (as-double (get data :physicsDt))
           :nvidia_isaac.SimScene/createdAt (now)
           :nvidia_isaac.SimScene/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-sim-scenes
  "List SimScene with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-sim-scenes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_isaac.SimScene/id))
         rows (apply-filters rows (:filter opts) [:nvidia_isaac.SimScene/name :nvidia_isaac.SimScene/assets :nvidia_isaac.SimScene/domainRandomized :nvidia_isaac.SimScene/physicsDt])]
     (paginate rows opts))))

(defn get-sim-scene
  "Retrieve a SimScene by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-sim-scene port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-sim-scene
  "Update a SimScene; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :nvidia_isaac.SimScene/name (get data :name)]))
                   (cond-> (contains? data :assets) (conj [:db/add id :nvidia_isaac.SimScene/assets (as-long (get data :assets))]))
                   (cond-> (contains? data :domainRandomized) (conj [:db/add id :nvidia_isaac.SimScene/domainRandomized (as-bool (get data :domainRandomized))]))
                   (cond-> (contains? data :physicsDt) (conj [:db/add id :nvidia_isaac.SimScene/physicsDt (as-double (get data :physicsDt))]))
                   (conj [:db/add id :nvidia_isaac.SimScene/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-sim-scene
  "Delete a SimScene."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Policy ────────────────────────────────────────────────────────────────
(defn create-policy
  "Create a Policy."
  [port data]
  (require-fields data ["algorithm" "checkpoint"])
  (let [id (new-id "isaac_pol")
        e {:db/id id
           :nvidia_isaac.Policy/id id
           :nvidia_isaac.Policy/skillId (get data :skillId)
           :nvidia_isaac.Policy/algorithm (get data :algorithm)
           :nvidia_isaac.Policy/checkpoint (get data :checkpoint)
           :nvidia_isaac.Policy/reward (as-double (get data :reward))
           :nvidia_isaac.Policy/createdAt (now)
           :nvidia_isaac.Policy/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-policies
  "List Policy with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-policies port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_isaac.Policy/id))
         rows (apply-filters rows (:filter opts) [:nvidia_isaac.Policy/skillId :nvidia_isaac.Policy/algorithm :nvidia_isaac.Policy/checkpoint :nvidia_isaac.Policy/reward])]
     (paginate rows opts))))

(defn get-policy
  "Retrieve a Policy by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-policy port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :skillId) (get rec :nvidia_isaac.Policy/skillId))
         (assoc :skillId-obj (-pull port (get rec :nvidia_isaac.Policy/skillId))))))))

(defn update-policy
  "Update a Policy; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :skillId) (conj [:db/add id :nvidia_isaac.Policy/skillId (get data :skillId)]))
                   (cond-> (contains? data :algorithm) (conj [:db/add id :nvidia_isaac.Policy/algorithm (get data :algorithm)]))
                   (cond-> (contains? data :checkpoint) (conj [:db/add id :nvidia_isaac.Policy/checkpoint (get data :checkpoint)]))
                   (cond-> (contains? data :reward) (conj [:db/add id :nvidia_isaac.Policy/reward (as-double (get data :reward))]))
                   (conj [:db/add id :nvidia_isaac.Policy/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-policy
  "Delete a Policy."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Sensor ────────────────────────────────────────────────────────────────
(defn create-sensor
  "Create a Sensor."
  [port data]
  (require-fields data ["modality" "rateHz"])
  (let [id (new-id "isaac_sen")
        e {:db/id id
           :nvidia_isaac.Sensor/id id
           :nvidia_isaac.Sensor/robotId (get data :robotId)
           :nvidia_isaac.Sensor/modality (get data :modality)
           :nvidia_isaac.Sensor/rateHz (as-double (get data :rateHz))
           :nvidia_isaac.Sensor/resolution (get data :resolution)
           :nvidia_isaac.Sensor/createdAt (now)
           :nvidia_isaac.Sensor/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-sensors
  "List Sensor with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-sensors port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_isaac.Sensor/id))
         rows (apply-filters rows (:filter opts) [:nvidia_isaac.Sensor/robotId :nvidia_isaac.Sensor/modality :nvidia_isaac.Sensor/rateHz :nvidia_isaac.Sensor/resolution])]
     (paginate rows opts))))

(defn get-sensor
  "Retrieve a Sensor by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-sensor port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-sensor
  "Update a Sensor; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :robotId) (conj [:db/add id :nvidia_isaac.Sensor/robotId (get data :robotId)]))
                   (cond-> (contains? data :modality) (conj [:db/add id :nvidia_isaac.Sensor/modality (get data :modality)]))
                   (cond-> (contains? data :rateHz) (conj [:db/add id :nvidia_isaac.Sensor/rateHz (as-double (get data :rateHz))]))
                   (cond-> (contains? data :resolution) (conj [:db/add id :nvidia_isaac.Sensor/resolution (get data :resolution)]))
                   (conj [:db/add id :nvidia_isaac.Sensor/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-sensor
  "Delete a Sensor."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Trajectory ────────────────────────────────────────────────────────────────
(defn create-trajectory
  "Create a Trajectory."
  [port data]
  (require-fields data ["waypoints" "durationS"])
  (let [id (new-id "isaac_tra")
        e {:db/id id
           :nvidia_isaac.Trajectory/id id
           :nvidia_isaac.Trajectory/robotId (get data :robotId)
           :nvidia_isaac.Trajectory/waypoints (as-long (get data :waypoints))
           :nvidia_isaac.Trajectory/durationS (as-double (get data :durationS))
           :nvidia_isaac.Trajectory/status (get data :status)
           :nvidia_isaac.Trajectory/createdAt (now)
           :nvidia_isaac.Trajectory/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-trajectories
  "List Trajectory with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-trajectories port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_isaac.Trajectory/id))
         rows (apply-filters rows (:filter opts) [:nvidia_isaac.Trajectory/robotId :nvidia_isaac.Trajectory/waypoints :nvidia_isaac.Trajectory/durationS :nvidia_isaac.Trajectory/status])]
     (paginate rows opts))))

(defn get-trajectory
  "Retrieve a Trajectory by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-trajectory port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-trajectory
  "Update a Trajectory; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :robotId) (conj [:db/add id :nvidia_isaac.Trajectory/robotId (get data :robotId)]))
                   (cond-> (contains? data :waypoints) (conj [:db/add id :nvidia_isaac.Trajectory/waypoints (as-long (get data :waypoints))]))
                   (cond-> (contains? data :durationS) (conj [:db/add id :nvidia_isaac.Trajectory/durationS (as-double (get data :durationS))]))
                   (cond-> (contains? data :status) (conj [:db/add id :nvidia_isaac.Trajectory/status (get data :status)]))
                   (conj [:db/add id :nvidia_isaac.Trajectory/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-trajectory
  "Delete a Trajectory."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/simrobots" :op :create :entity "SimRobot"}
   {:method "GET" :path "/v1/simrobots" :op :list :entity "SimRobot"}
   {:method "GET" :path "/v1/simrobots/:id" :op :get :entity "SimRobot"}
   {:method "PATCH" :path "/v1/simrobots/:id" :op :update :entity "SimRobot"}
   {:method "DELETE" :path "/v1/simrobots/:id" :op :delete :entity "SimRobot"}
   {:method "POST" :path "/v1/skills" :op :create :entity "Skill"}
   {:method "GET" :path "/v1/skills" :op :list :entity "Skill"}
   {:method "GET" :path "/v1/skills/:id" :op :get :entity "Skill"}
   {:method "PATCH" :path "/v1/skills/:id" :op :update :entity "Skill"}
   {:method "DELETE" :path "/v1/skills/:id" :op :delete :entity "Skill"}
   {:method "POST" :path "/v1/simscenes" :op :create :entity "SimScene"}
   {:method "GET" :path "/v1/simscenes" :op :list :entity "SimScene"}
   {:method "GET" :path "/v1/simscenes/:id" :op :get :entity "SimScene"}
   {:method "PATCH" :path "/v1/simscenes/:id" :op :update :entity "SimScene"}
   {:method "DELETE" :path "/v1/simscenes/:id" :op :delete :entity "SimScene"}
   {:method "POST" :path "/v1/policies" :op :create :entity "Policy"}
   {:method "GET" :path "/v1/policies" :op :list :entity "Policy"}
   {:method "GET" :path "/v1/policies/:id" :op :get :entity "Policy"}
   {:method "PATCH" :path "/v1/policies/:id" :op :update :entity "Policy"}
   {:method "DELETE" :path "/v1/policies/:id" :op :delete :entity "Policy"}
   {:method "POST" :path "/v1/sensors" :op :create :entity "Sensor"}
   {:method "GET" :path "/v1/sensors" :op :list :entity "Sensor"}
   {:method "GET" :path "/v1/sensors/:id" :op :get :entity "Sensor"}
   {:method "PATCH" :path "/v1/sensors/:id" :op :update :entity "Sensor"}
   {:method "DELETE" :path "/v1/sensors/:id" :op :delete :entity "Sensor"}
   {:method "POST" :path "/v1/trajectories" :op :create :entity "Trajectory"}
   {:method "GET" :path "/v1/trajectories" :op :list :entity "Trajectory"}
   {:method "GET" :path "/v1/trajectories/:id" :op :get :entity "Trajectory"}
   {:method "PATCH" :path "/v1/trajectories/:id" :op :update :entity "Trajectory"}
   {:method "DELETE" :path "/v1/trajectories/:id" :op :delete :entity "Trajectory"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"simrobots" {:create create-sim-robot :list list-sim-robots :get get-sim-robot :update update-sim-robot :delete delete-sim-robot}
   "skills" {:create create-skill :list list-skills :get get-skill :update update-skill :delete delete-skill}
   "simscenes" {:create create-sim-scene :list list-sim-scenes :get get-sim-scene :update update-sim-scene :delete delete-sim-scene}
   "policies" {:create create-policy :list list-policies :get get-policy :update update-policy :delete delete-policy}
   "sensors" {:create create-sensor :list list-sensors :get get-sensor :update update-sensor :delete delete-sensor}
   "trajectories" {:create create-trajectory :list list-trajectories :get get-trajectory :update update-trajectory :delete delete-trajectory}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "nvidia_isaac-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
